name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin' # Ou 'oracle' si Temurin n'est pas encore prÃªt pour la v25
          cache: maven
      - name: Build and Test with Maven
        run: mvn clean install --file demo-app/pom.xml
      - name: Build JAR
        run: mvn clean package -f demo-app/pom.xml
      - name: Build Docker Image
        run: docker build -t math208/demo-app:latest .
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push Docker Image
        working-directory: ./demo-app
        run: docker push math208/demo-app:latest
